

all: ringmaster player

ringmaster: ringmaster.cpp potato.h webuser.h
	g++ -g -o ringmaster ringmaster.cpp
player: player.cpp potato.h webuser.h
	g++ -g -o player player.cpp 
clean:
	rm -rf ringmaster player